Issue 3250/make all template repositories actual
jdi-templates/jdi-light-junit-template pull request #8
Opened 2021-08-20 11:59 UTC by n-ton4

2021-08-23 15:47 UTC, pnatashap requested changes
в jdi-light guava другой версии, надо все синхронизировать
<dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>30.1-jre</version>
        </dependency>

2021-08-25 10:30 UTC, n-ton4 commented
> в jdi-light guava другой версии, надо все синхронизировать
> 
> com.google.guava
> guava
> 30.1-jre

полагаю эту зависимость надо просто удалить из этого темплейта

2021-08-26 15:39 UTC, pnatashap requested changes
Если посмотреть лог запуска - там ни одного теста не запустилось, явно что-то не так.

[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

2021-08-26 15:39 UTC, pnatashap commented on .github/workflows/maven.yml
> +        id: ftests
последним шагом должна быть проверка состояния этого шага. падаем, если тут были падения

2021-08-26 15:39 UTC, pnatashap commented on pom.xml
> +        <jdi.version>1.3.13</jdi.version>
14 версия

2021-08-26 15:39 UTC, pnatashap commented on .github/workflows/maven.yml
> +        run: mvn test
-ntp добавь, чтобы лог от загрузки не проматывать

2021-08-27 13:57 UTC, n-ton4 commented on .github/workflows/maven.yml
> +        id: ftests
это лишнее. билд упадет, если тесты не прошли

2021-08-27 14:05 UTC, n-ton4 commented on pom.xml
> +        <jdi.version>1.3.13</jdi.version>
> Если посмотреть лог запуска - там ни одного теста не запустилось, явно что-то не так.
> 
> [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

Надо разбираться в JDISetupExtension, без него тесты запускаются, но падают. Это мне видится отдельной задачей.

2021-09-06 14:11 UTC, knadonenko approved these changes

2021-09-06 14:18 UTC, merged